### ISSUE TITLE
`responseMimeType` parameter is missing for `gemini-1.5-pro`

### ISSUE THREAD

**Issue by marius-ciocoiu** [googleapis/nodejs-vertexai#334]
As is stated in the [documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini#parameters) for model `gemini-1.5-pro` we should be able to use the parameter `responseMimeType` in the request body.

**Comment by pierznewton-john** [comment]
Not only that, but the responseSchema option is missing. You can still add it, but the typescript types do not document it, so it's hard to know it exists unless you refer to the online documentation.

**Comment by yoichiro** [comment]
@marius-ciocoiu The `responseMimeType` has been supported by https://github.com/googleapis/nodejs-vertexai/pull/380. You can use it.
@pierznewton-john This issue is about the `responseMimeType`, not the `responseSchema`. You need to create a new issue about `responseSchema`.
@yyyu-google @happy-qiao I guessthat you can close this issue. Could you confirm this?

**Comment by marius-ciocoiu** [comment]
Thank you @yoichiro !
